lib/cmds/w_truncate.py
This addresses the issue reported in westpa/west_tools#4 and gives explicit recommendations to the user to remove file-system data corresponding to truncated iterations.
=> Add warning to w_truncate to remove corresponding file-system data

lib/examples/nacl_amb/env.sh, lib/examples/nacl_gmx/env.sh, lib/examples/nacl_namd/env.sh, lib/examples/nacl_openmm/env.sh, lib/examples/odld/env.sh
On OSX `readlink` doesn't use `-f` flag for the same purpose as on Linux, so users attempting to use the `env.sh` script in all of the examples will get an error. 
I modified all of the `env.sh` scripts to bail if `WEST_ROOT` wasn't set, giving a message that the user should specify it. An alternative option would have been to use python as in the `west` shell script to make it platform agnostic. I chose not to take that path because I could imagine a user copying an example directory to a new location, and then the assumed position in the file hierarchy would not hold. The same is not true of the `west` script, which should always live in the same place.
=> Force users to explicitly set WEST_ROOT in examples

doc/tutorials/amber.rst, lib/examples/nacl_amb/aux_functions.py, lib/examples/nacl_amb/env.sh, lib/examples/nacl_amb/west.cfg
Removed export of AMBERHOME line in env.sh in Na/Cl example.  Instead, it checks to see if the environment variable exists, and fails out with an error message if it doesn't.
While cpptraj/pmemd may exist on the path, if amberhome isn't set, it's unlikely that the libraries are in the LD_LIBRARY_PATH variable, and so it likely won't work.
=> Fixed Amber Example

doc/conf.py, doc/development/api.rst, doc/readme_sphinx.rst, doc/sphinx_index.rst
I made a slight error with a subheader in the previous pull request which is fixed. I also started a [test page](https://asinansaglam.github.io/westpa/development/api.html) for the API documentation using [Sphinx autodoc extension](http://www.sphinx-doc.org/en/stable/ext/autodoc.html#module-sphinx.ext.autodoc). 
Currently only includes binning and yamlcfg modules and WESTRC class. Also includes every member of each, even ones without documentation at the moment.
=> Minor subheader mismatch fix and an auto generated API test

src/west/data_manager.py, src/west/sim_manager.py
Updates in this pull request accommodate changes to h5py and numpy in the latest version 4.4.0 of Anaconda Python, which previously would cause WESTPA simulations not to initialize or run.  These updates are also compatible with previous versions of Anaconda; my tests with Anaconda 4.3.1 and 4.1.11 have been successful, though I cannot guarantee compatibility with versions intermediate or previous to those.  
This update also resolves an error when attempting to use the sec2 or family drivers for HDF5 files, which was present in both the present and previous versions of Anaconda.
=> Compatibility with latest version of Anaconda (2-4.4.0)

lib/examples/nacl_amb/run.sh, lib/examples/nacl_gmx/run.sh, lib/examples/nacl_gmx_5.0.4/run.sh, lib/examples/nacl_namd/run.sh
Na+/Cl- tutorials now use the processes work manager by default. This is important for the following reasons:
- Na+/Cl- tutorials already stated that WESTPA would use all available processors by default.
- The Na+/Cl- tutorials can be slow to run in serial mode (the default).
- With the introductory tutorials, we should highlight how WESTPA can easily run simulations in parallel.
=> Na+/Cl- Tutorials now use "processes" work manager by default.

lib/west_tools/w_ipa.py
Due to an off-by-one error, the w.trace method from w_ipa previously traced segments from the previous iteration, rather than the current iteration.  This is fixed now.
=> Fix the w.trace method from w_ipa

lib/west_tools/westpa/binning/assign.py
While this fix works for me, I am requesting a code review since I am not familiar with this part of the code.
Multiple level-recursions with multi-dimensional progress coordinates did not work previously; on the first call to `add_mapper`, `replaces_bin_at` is expanded to 2 dimensions, causing a `ValueError` on the second call to `add_mapper`, where WESTPA enforced that `replaces_bin_at.shape[1]` is less than two. To fix this, in multi-level recursions we now instead pass `replaces_bin_at` to `add_mapper`, with the extra dimension removed.
For example, if we call `my_mapper.add_binmapper(mapper, [0,0])`, and `[0,0]` falls within a bin already replaced with new binmapper, then previously we called `self.recursion_targets[ibin].add_binmapper(mapper, [[0,0]])`, which would generate an error …
=> Fix for multiple-level recursions with recursive binmapper

lib/west_tools/westpa/kinetics/_kinetics.c, lib/west_tools/westpa/kinetics/_kinetics.pyx
Occasionally, the rate constant calculation from w_direct would return 0, even when there was probability in the istate AND a flux into the jstate.
This was caused by the rate normalization step for pairwise rate calculations (which is done by default); if no walkers had entered either the i or jstate, the sum of their probability was 0, which the istate probability was divided by, thus becoming 0/0, or NaN.  Once NaN exists in the dataset, any number interacting with NaN also becomes NaN; in that event, the code would return a 0 for the rate.
Now, if no probability has or does exist in the i or jstate, we don't do the pairwise rate normalization (and instead simply add 0 to the probability running average).  This problem primarily affected simulations where the bstates were different …
=> Fixed routine for rate calculation from w_direct.

lib/examples/nacl_amb/init.sh, lib/examples/nacl_amb_gb/init.sh, lib/examples/nacl_gmx/init.sh, lib/examples/nacl_gmx_5.0.4/init.sh, lib/examples/nacl_gmx_gb/init.sh, lib/examples/nacl_namd/init.sh, lib/examples/nacl_namd_gb/init.sh, lib/examples/nacl_openmm/init.sh, lib/examples/odld_exe/init.sh, lib/examples/wca-dimer_openmm/we_custom/init.sh, lib/examples/wca-dimer_openmm/we_exec/init.sh
Adam requested that I remove the pkill commands from the init.sh scripts.  Testing with the odld_exe example suggests this is safe.
=> Removed pkill from initialization scripts, at request of @ajoshpratt

lib/west_tools/w_assign.py, lib/west_tools/westtools/binning.py
This small change brings w_assign on par with w_bins in pulling the latest bin mapper from the master h5 file. Currently w_assign will pull the first bin mapper created/bin mapper from the system.py from what I can tell from my tests. I additionally propose to enable --bins-from-h5file argument for w_assign and make it an integer argument instead of a store_true argument, allowing the user to select the iteration to pull the bin mapper from. **Sneaky edit:** Another option is to just add a secondary argument to select the particular iteration of course, which I'm starting to lean towards after playing with this. 
Pulling the latest mapper is necessary for supporting adaptive binning schemes and it's nice to allow the user to select a particular iteration to pull the mapper from as well. …
=> Allow w_assign to pull the latest bin mapper and allow to pull bin mapper from a particular iteration

lib/west_tools/westtools/wipi.py
The previous behavior checked `seg_ids == None`, which raises an error if `seg_ids` is defined. This was addressed by wrapping the whole thing in a try/except block.
However, the intended behavior can be produced by just checking with `is` instead of `==`, which correctly evaluates to `False` if `seg_ids` is defined instead of erroring out. Although the contents of the try block are fairly simple, doing the evaluation this way without the unnecessary try block prevents other potential errors in the block from being incorrectly ignored.
=> Minor bugfix: Changed check for seg_id defined

miniconda_install_westpa.sh
After this is merged, then all installation methods will use release 2020.02.
=> Updated miniconda_install_westpa.sh to use release 2020.02.

.github/workflows/test.yaml, setup.py, tests/test_binning.py
Add more information to `setup.py` to facilitate building from scratch with pip without first installing dependencies via conda. Also, mark failing binning test as expected to fail to facilitate full test of github actions.
=> More infrastructure

tests/test_sim_manager.py
Previously, the _sim_manager attribute of westpa.rc was cleared, but the _system was not. This resulted in state change persisting after the test completed, which adversely affected subsequent tests.
=> Fix: clear westpa.rc state on teardown

src/westpa/core/states.py
If no auxref is provided for a state (it's an optional parameter) then `state.auxref` will be set to `None`. To play nicely with the string formatting, this `None` object must be cast to a string `"None"`
=> Bugfix for states when auxref is None

src/westpa/core/_rc.py
Added a function `clear_state` to westpa.rc that wipes out state. This is useful for ensuring no "leftover state" persists (such as between tests)
=> Added function to rc to clear state

src/westpa/oldtools/aframe/plotting.py
New
A [recent update in matplotlib (3.4.0)](https://matplotlib.org/stable/api/api_changes.html?highlight=revcmap) removed the `matplotlib.cm.revcmap` method. This leads to the [CI dying when running w_succ test](https://github.com/westpa/westpa/runs/2353249919?check_suite_focus=true#step:6:25).
The corresponding line is changed to use the [newer method](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.LinearSegmentedColormap.html#matplotlib.colors.LinearSegmentedColormap.reversed) …
=> Removed revcmap in oldtools/aframe/plotting.py

src/westpa/core/data_manager.py, src/westpa/tools/binning.py
#142 #146  
Fixes so WESTPA checks for the the bytes version of the hashval. It should eliminate duplicate bin_mappers and errors when running w_assign
**Status.**
=> Binhash error fix (WESTPA 2.0)

src/westpa/tools/wipi.py
#157 
As per @synapticarbors, ``__div__`` and ``__rdiv__`` are replaced by ``__truediv__`` and ``__rtruediv__`` in ``wipi.py``. Those older functions no longer exist in Python 3 and don't work anyway.
**Status.**
=> fixed div and rdiv in wipi.py

src/westpa/westext/adaptvoronoi/adaptVor_driver.py, src/westpa/westext/stringmethod/string_driver.py, src/westpa/westext/stringmethod/string_method.py, src/westpa/westext/weed/weed_driver.py, src/westpa/westext/wess/wess_driver.py
Updated imports in plugins to be westpa-2.0 compatible.
Adding a new plugin, even with correct imports, still causes the top-level  `__init__.py` to be imported, which in turn imports all the plugins `__init__.py`s. Since they had broken, old-style imports, this broke WESTPA when using any plugin at all, if a plugin with broken imports existed.
**Status.**
**Additional context.** Add any other …
=> Updated plugins to westpa 2.0-compatible imports

src/westpa/core/trajectory.py
There is a bug when h5 file is used as the trajectory format in MD production, and no topology file is returned (as h5 files usually contain topology information within them). The h5 file may be considered as a topology file instead of a trajectory file. Even though h5 files may be used as a topology file but I think it is a very edge use case and it is probably better when always consider them as trajectory. 
**Major …
=> Fixed a problem when h5 is used as the trajectory output in the HDF5 framework

lib/west_tools/w_trace.py
w_trace breaks when using h5py 3. This is due to the fact that h5py 3 defaults to 'r' mode by default but h5py 2 defaults to 'a'. This is a slip-streamed fix.
**Status.**
=> Fix w_trace for h5py 3

src/westpa/cli/tools/w_trace.py
w_trace breaks when using h5py 3. This is due to the fact that h5py 3 defaults to 'r' mode by default but h5py 2 defaults to 'a'.
**Status.**
=> Fixed a bug in w_trace that resulted from h5py 3.0 upgrade

lib/west_tools/plothist.py
…ing else
#202 
The y axis label for the 'energy' mode of plothist contained a delta F(X) which might be misleading. I have instead changed the axis label to be more consistent with the other plotting modes.
This is a backport of #202 and co-Authored by: @atbogetti 
**Status.**
=> Changed y-axis label of plothist energy to be consistent with everything

src/westpa/core/data_manager.py
Fix a typo in the key used to access the initial state progress coordinates (`'pcoord'` -> `'istate_pcoord'`).
- []
- westpa/core/data_manager.py
**Status.**
=> Fix KeyError in WESTDataManager.get_initial_states().

src/westpa/cli/core/w_init.py, src/westpa/core/data_manager.py, src/westpa/core/propagators/executable.py, src/westpa/core/sim_manager.py, src/westpa/core/states.py
Start states do not work with the HDF5 Framework. This PR fixes that by allowing the propagator to read the start states structure files directly (since they are not saved into any of the per-iteration HDF5 files). 
As a bonus, I expanded the docstrings in src/westpa/core/states.py and fixed some typo errors here and there.
Should be merged after #220 since it contains those changes. (Or just close #220 and merge this one directly)
**Goals and Outstanding Issues.** A clear and concise list of goals (to be) …
=> Making Start States Compatible with the HDF5 Framework

src/westpa/westext/__init__.py
As it currently stands, all plugins are loaded at once when any one of the plugins are needed. This means ``msm_we`` dependencies (for the haMSM restarting plugin) are necessary to run all other plugins. I removed the contents in ``src/westpa/westext/__init__.py `` so it won't load everything when `westext` is loaded (i.e. when specified in west.cfg as part of another plugin).
Tested on ODLD by running WESS and Restarting Plugin in an environment without msm_we and its dependencies. 
**Goals and Outstanding …
=> Decoupling all plugins in westext

src/oldtools/aframe/plotting.py
#169 
Current code in `src/oldtools/aframe/plotting.py` uses a deprecated/removed matplotlib feature which breaks `w_succ`. This is a back-port of a WESTPA 2.0 fix to WESTPA 1.0.
**Status.**
=> port of PR #169 to WESTPA 1.0

lib/west_tools/plothist.py
#213 and  #202 #203 #210
Misc fixes to address `images.append` deprecation (resolves #213) and remove the [kT<sup>-1</sup>] references in plothist.
Basically the same PR as #241 , but for WESTPA 1.0.
**Status.**
=> WESTPA 1.0 Plothist misc fix
