westpa/westpa

doc/Makefile
doc/sphinx_index.rst

Just a small update to sphinx documentation to include links to WESTPA workshop talks. Another pull request to ghpages repo will be put up right after this, this just updates the sphinx documentation.

Small update to the documentation

---

publications.html

Added two new publications to the publications page.

New publications

---

publications.html

Small style fixes and updated publications list.

Updated publications, Jan. 2017

---

README.rst
doc/users_guide/hdf5.rst
doc/users_guide/west/setup.rst
src/west/tests/test_we_driver.py

A paragraph was added to "Getting started", a form link was added. 
I will make another pull request in a second for the same updates in the Sphinx documentation.

Some changes to README 

---

index.html

Just a bit of rewriting/reordering and a removal of a link to the old wiki page.

Small changes to the get help section

---

doc/tutorials/amber.rst
lib/examples/nacl_amb/aux_functions.py
lib/examples/nacl_amb/env.sh
lib/examples/nacl_amb/west.cfg

This needs to be merged along with the updates to the website!  I first want to merge the changes into Adam's nacl_fix branch so he can get credit for his changes.

Amber Na+/Cl- tutorial now specifies WE parameters via YAML rather than system.py

---

README.rst
doc/readme_sphinx.rst
doc/sphinx_index.rst
doc/users_guide/checklist.rst
doc/users_guide/faq.rst

Added FAQ page, temporarily created a separate copy of the readme file for Sphinx use (will automate this in the future instead), minor content changes to checklist and Sphinx documentation landing page.

Checklist/FAQ changes, master pull request

---

doc/sphinx_index.rst
doc/users_guide/faq.rst

Added a question to FAQ, minor changes to tutorial titles. Pull request for master branch.

Minor FAQ/tutorial changes, master pull request

---

README.rst
doc/readme_sphinx.rst

Updated installation instructions for the main README page as well as the documentation rst file.

Installation instructions update

---

.westpa_gen.py
setup.sh

Hi,
This is a pretty trivial patch to make a csh equivalent of westpa.sh
Alan

add support for csh and derived shells

---

miniconda_install_westpa.sh

This is the script for automatically installing Miniconda followed by WESTPA referenced in the documentation
https://github.com/westpa/westpa/wiki/Installing-WESTPA

Added script for installing Miniconda followed by WESTPA

---

miniconda_install_westpa.sh

Here's the update miniconda script updated for Py3.

Added Py3 version of Miniconda install script

---

publications.html

Added "Optimizing weighted ensemble sampling of steady states."

New Publication

---

publications.html

- Added two new sections, added the WE review paper from 2017, moved tutorials around, and fixed typos.

New sections and papers in publications.html

---

.github/workflows/test.yaml
README.rst

Fixes for #143 (for the 2.0 Branch) and also updates to the Github Action CI to include tests for Python 3.9
Github Action CI settings are updated so they are tested on Ubuntu 20.04 and on Python 3.9 as well. The installation (dev-env) test is left on python 3.8 since it's much quicker.
**Status.**

Documentation Update and Github Action CI Updates to run on Ubunutu 20.04 and Python 3.9

---

src/westpa/core/_rc.py
src/westpa/core/propagators/executable.py
src/westpa/core/we_driver.py
tests/test_we_driver.py

Closed an earlier pull request. This one includes changes Jeremy made to get GH actions working again.
Adding in Audrey's split/merge scheme into WESTPA 2.0 to enable other grouping function methods.
- src/westpa/core/_rc.py 
- src/westpa/core/propagators/executable.py
- src/westpa/core/we_driver.py
**Status.**
**Additional context.** Add any other context or screenshots about the pull request …

Modifications to enable binless strategies using an external function.

---

src/westpa/westext/weed/UncertMath.py

**PR Based on** #157 
**Describe the changes made.** 
Extending the fix for #157  to branch `westpa-2.0-restruct` based on @synapticarbors's suggestion.
- https://github.com/westpa/westpa/blob/6df148c742876c4edbdac632039d01bd04b87ad3/src/westpa/westext/weed/UncertMath.py#L129
**Status.**

westpa-2.0-restruct : Minor tweak in weed plugin to make it python 3.x compatible

---

README.rst
src/westpa/core/propagators/executable.py

Elaborated on an error message when pcoord is incorrectly calculated/not found. Pull request is remade (#137)  due to major changes in the `westpa-2.0-restruct` branch.
**Status.**

2.0 error messages for pcoord errors

---

doc/users_guide/wwmgr.rst
pyproject.toml
src/westpa/core/_rc.py

#172 #90 
Fixes for CI issues where pep 517 is not recognized during installation. It was a new error that started with the new pip solver. For more info on the new pip resolver, read Issue #172.
Also included the changes from #90 into this, since it's only a documentation change. (resolves #90)
Also removed the [deprecated np.int alias](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated) into int. No change in functionality.
**Goals and Outstanding …

TEMP Fix for CI

---

src/westpa/cli/tools/w_bins.py

`w_bins` doesn't really work as is (it crashes because some legacy `load_auxdata` option is missing). Removed that and added an option to specify the iteration you would like to rebin (which is a copy/paste from `w_bins info`).
**Status.**

w_bins fix

---

src/westpa/tools/kinetics_tool.py

fixes #129 
Fixes the progress bar of kinetics_tool due to deprecation in numpy. 
**Status.**

Kinetics Tool fix (Numpy 1.19 deprecation)

---

lib/west_tools/w_bins.py
lib/west_tools/w_multi_west.py
lib/west_tools/westtools/kinetics_tool.py
lib/wwmgr/work_managers/core.py
miniconda_install_westpa.sh

fixes #129  fixes #107  
#184 #190 
Fixed two long standing bugs: progress bar of kinetic tools (due to numpy 1.19) and a isinstance() call (which was fixed in 2.0). This is needed so we're completely compatible with numpy 1.19 (which is tied to publishing on conda on python 3.9).
#129 
Implemented what Josh said in his post + some little change for normalization of the load bar. The progress bar now tracks per iteration instead of per calculation (as far as I can tell) so it might be less sensitive to changes. …

2020.05 - Bug fixes

---

src/westpa/tools/binning.py

#186 
#186 introduced some conflicting changes. This rolls that one conflicting change back, to be evaluated later.
**Status.**

Rolling back binhash fix from #186

---

src/westpa/analysis/core.py

Refactoring of `westpa.analysis.core`.
*Main Issue:* The original implementation of the `recycled_walkers` property (an analog of w_succ) was very slow, because (I am embarrassed to say) it relied on deserializing bin mappers and explicitly checking whether walkers stopped in the sink. The new implementation follows that of [w_succ](https://github.com/westpa/westpa/blob/9dc62478fcef0001b9c038cd56a40b6be1b9d64a/lib/cmds/w_succ.py).
A secondary issue was the awkwardness/unnecessary restrictiveness imposed by …

Analysis module refactoring 

---

src/westpa/core/data_manager.py
src/westpa/core/propagators/executable.py
src/westpa/core/trajectory.py

Addresses the comments in #189.
Added docstrings for HDF5-related functions and classes. Regarding the user-end modifications and API usages, I will add them to the Wiki page and the tutorial paper. This PR is docstring only.
**Status.**

Docstring for HDF5 framework-related functions and classes

---

src/westpa/core/data_manager.py
src/westpa/core/trajectory.py

- Added version history for WEST HDF5 version 8.
- Fixed a bug where MDTraj-supported topology format extensions were accidentally modified.
**Status.**

Added version history for WEST HDF5 version 8 and a minor bug fix

---

src/westpa/analysis/trajectories.py

Removed the one remaining use of the `functools.cached_property()` decorator in the analysis module. This avoids an unnecessary dependence on Python >=3.8, and resolves an inconsistency with the Python version requirement in setup.py (>=3.6).
- Remove Python >=3.8 requirement.
- westpa/analysis/trajectories.py
**Status.**
**Additional context.** Add any other context or screenshots about the pull …

Remove @cached_property attributes

---

src/westpa/cli/tools/plothist.py

- The y axis label for the 'energy' mode of plothist contained a delta F(X) which might be misleading.  I have instead changed the axis label to be more consistent with the other plotting modes. 
**Status.**

Changing y-axis label for plothist 'energy' mode

---

setup.py

mdtraj is required twice in setup.py (once in full install, once as tests)
**Status.**

fix mdtraj duplicate requirements

---

.github/workflows/test.yaml

None
I have tested and found that with MDTraj 1.9.7, we can finally install WESTPA on Python 3.10 without errors. As such, I have added Py 3.10 to the CI to keep track of potential problems.
https://github.com/jeremyleung521/westpa/runs/4413099287?check_suite_focus=true
**Status.**

add python 3.10 to the list for CI

---

src/westpa/analysis/README.rst
src/westpa/analysis/core.py
src/westpa/analysis/trajectories.py

The initial version of the `BasicMDTrajectory` reader relied on symbolic links (e.g., parent.xml) that may not exist post-simulation. Though we may keep these links around in the future (see https://github.com/westpa/westpa_tutorials/pull/25 and https://github.com/westpa/westpa_tutorials/pull/26), for the sake of backward-compatibility and user convenience, it seems best to avoid relying on them. This PR changes the implementation of `BasicMDTrajectory` accordingly.
Also included are two small additions to the …

Fix BasicMDTrajectory reader

---

src/westpa/analysis/core.py

#225 
This PR addresses problems initially reported by @jeremyleung521 in https://github.com/westpa/westpa/pull/217#issuecomment-1018735223. It also includes a small performance enhancement of `Walker.children`.
**Goals and Outstanding Issues.** A clear and concise list of goals (to be) accomplished.
- Handle the case that the final iteration in the west.h5 file (`west_current_iteration`) is complete (e.g. after `w_truncate`ing the run).
- Avoid an `IndexError` when the parent of a walker is an initial state that …

Fix for issue #225

---

README.rst
doc/readme_sphinx.rst

#232
This is basically #232 but for the dev releases. That PR should be merged after 2.0 has officially been released. Both of these PRs are updates of the documentation. This specific PR includes WESTPA installation instructions for the dev versions.
I also clarified the language so it's clear that we recommend anaconda to be installed (for python version control) regardless of which method.
**Major files changed.** …

modified README for sphinx and project for interim 2.0 dev releases

---

CITATION.bib
README.rst

Adding in a CITATION.bib file so users can cite the WESTPA papers quickly. It'll also show up on the sidebar when this branch gets rebased. Also added in badges that link to our google groups + anaconda + our tutorial githubs.
**Status.**

WESTPA2 Github Misc Update

---

CITATION.bib
README.rst

Adding in a CITATION.bib file so users can cite the WESTPA 1.0 paper quickly. It'll also show up on the sidebar.
Also added in badges that link to our google groups in README.rst.
**Status.**

WESTPA1 GH Misc Update
